Projeto Final PF2;Ruben Carlo Benante;rcb@beco.cc;71;beco;@drbeco;Blossom;1;Programa2
1;8;8;8;8;8;8;Cesar Henrique Soares Pereira;cesar.soarespereira@upe.br;chsp;@cesarsoarespereira-dot;m
0;8;8;8;8;8;8;Lucas Enrique Coutinho Parente;lecp@poli.br;lecp;@lrccaa;s
0;8;8;8;8;8;8;Bernardo Cavalcanti Lamas;bernardo.lamas@upe.br;bcl;@bergtoso;s
0;8;8;8;8;8;8;Nicoly Nunes dos Santos;nicoly.santos@upe.br;nnds;@Nicoly-Santos;s
0;8;8;8;8;8;8;Ana Clara Alexandre De Freitas;acaf1@poli.br;acaf1;@ana-cl;s
0;8;8;8;8;8;8;Ana Clara Alexandre De Freitas;acaf1@poli.br;acaf1;@ana-cl;s
0;8;8;8;8;8;8;Arthur Gabriel Damascena Alves Da Costa;arthur.gdacosta@upe.br;agdadc;@Arthurg4briel;s
0;8;8;8;8;8;8;Gyovanna Lauren Franca Borges;gyovanna.lauren@upe.br;glfb;@gyovanna-laurenfb;s
0;8;8;8;8;8;8;Leo Bizzocchi Kusunoki;leo.kusunoki@upe.br;lbk;@BizzoK;s
0;8;8;8;8;8;8;Luiz Paulo Santana Do Nascimento;luiz.paulosantana@upe.br;lpsdn;@LUIZPAULOSN;s
